sonar.organization=secops-study-wp
sonar.projectKey=secops-study-wp

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.java.source=1.8
